import { Garment, Occasion } from '@/types/garment';
import { LogMap } from '@/types/log';
import { OutfitCombo } from '@/types/outfit';
import { daysSinceWorn } from '@/lib/history/log';

const NEUTRALS = new Set(['black','white','grey','brown']);
const COMPAT: Record<string,string[]> = { red:['red','orange','purple','pink','black','white','grey'], orange:['orange','red','yellow','blue','black','white','grey'], yellow:['yellow','orange','green','blue','black','white','grey'], green:['green','yellow','blue','brown','black','white','grey'], blue:['blue','green','purple','orange','black','white','grey','brown'], purple:['purple','red','blue','pink','black','white','grey'], pink:['pink','red','purple','black','white','grey'], grey:['grey','black','white','red','blue','green','purple','pink','orange','yellow'], black:['black','white','grey','red','orange','yellow','green','blue','purple','pink','brown'], white:['white','black','grey','red','orange','yellow','green','blue','purple','pink','brown'], brown:['brown','green','blue','orange','black','white','grey'] };
function colorScore(a?: string,b?: string){ if(!a||!b) return 0; if(a===b) return 2; if(NEUTRALS.has(a)||NEUTRALS.has(b)) return 3; return COMPAT[a]?.includes(b)?2:-2; }
function occasionScore(g:Garment,o:Occasion){ return g.occasion===o?4:2; }
function comboScore(t:Garment,b:Garment,s:Garment,o:Occasion,log:LogMap){ return colorScore(t.colorBucket,b.colorBucket)+colorScore(t.colorBucket,s.colorBucket)+colorScore(b.colorBucket,s.colorBucket)+occasionScore(t,o)+occasionScore(b,o)+occasionScore(s,o)+(t.favorite?2:0)+(b.favorite?2:0)+(s.favorite?2:0)+Math.min(daysSinceWorn(log,t.id),14)*.15+Math.min(daysSinceWorn(log,b.id),14)*.15+Math.min(daysSinceWorn(log,s.id),14)*.15; }
export function generateAllOutfits(garments:Garment[],occasion:Occasion,log:LogMap,includeAcc=false,includeCap=false):OutfitCombo[]{ const tops=garments.filter(g=>g.status==='disponible'&&(g.category==='top'||g.category==='dress')); const bottoms=garments.filter(g=>g.status==='disponible'&&g.category==='bottom'); const shoes=garments.filter(g=>g.status==='disponible'&&g.category==='shoes'); const acc=garments.filter(g=>g.status==='disponible'&&g.category==='accessory'); const caps=garments.filter(g=>g.status==='disponible'&&g.category==='cap'); const out:OutfitCombo[]=[]; for(const t of tops) for(const b of bottoms) for(const s of shoes){ const base={top:t.id,bottom:b.id,shoes:s.id,score:comboScore(t,b,s,occasion,log)}; if(includeAcc&&acc.length) for(const a of acc) out.push({...base,accessory:a.id,score:base.score+occasionScore(a,occasion)+colorScore(t.colorBucket,a.colorBucket)}); else if(includeCap&&caps.length) for(const c of caps) out.push({...base,cap:c.id,score:base.score+occasionScore(c,occasion)+colorScore(t.colorBucket,c.colorBucket)}); else out.push(base); } return out.sort((a,b)=>b.score-a.score).slice(0,30); }
export function generateStyleReasoning(combo:OutfitCombo,garments:Garment[],occasion:Occasion){ const ids=[combo.top,combo.bottom,combo.shoes,combo.accessory,combo.cap].filter(Boolean) as string[]; const items=ids.map(id=>garments.find(g=>g.id===id)).filter(Boolean) as Garment[]; const hasNeutral=items.some(g=>NEUTRALS.has(g.colorBucket||'')); return `Propuesta para ${occasion}: ${hasNeutral?'la base neutra facilita combinar las prendas':'los colores crean una combinación equilibrada'}. Se prioriza además la rotación y tus favoritos.`; }
