"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { AppSettings, Garment, SavedOutfit, makeId, wardrobeStore } from "../lib/wardrobe";

type Screen = "inicio" | "armario" | "armario-abierto" | "categorias" | "detalle" | "anadir" | "generador" | "resultado" | "editor" | "outfits" | "historial" | "ajustes";

const categoryNames = ["Tops", "Vestidos", "Pantalones", "Faldas", "Abrigos", "Zapatos", "Bolsos", "Accesorios"];
const categoryEmoji: Record<string,string> = { Tops:"👕", Vestidos:"👗", Pantalones:"👖", Faldas:"🩷", Abrigos:"🧥", Zapatos:"👟", Bolsos:"👜", Accesorios:"🕶️" };
const occasions = ["Informal", "Salir", "Elegante", "Noche", "Trabajo", "Evento"];

function Icon({ name }: { name: string }) {
  const p: Record<string,string> = {
    home:"M3 10.5 12 3l9 7.5v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z", closet:"M5 4h14v16H5z M8 8h2 M14 8h2 M8 12h8 M8 16h8",
    outfits:"M6 4h12v16H6z M9 8h6 M9 12h6 M9 16h4", settings:"M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm0-5v2m0 13v2M4.2 5.2l1.4 1.4m12.8 12.8 1.4 1.4M2 12h2m16 0h2M4.2 18.8l1.4-1.4m12.8-12.8 1.4-1.4",
    arrow:"M5 12h13m-5-5 5 5-5 5", back:"M19 12H5m6-6-6 6 6 6", search:"m20 20-4.2-4.2m2-5.3a7.3 7.3 0 1 1-14.6 0 7.3 7.3 0 0 1 14.6 0Z", plus:"M12 5v14M5 12h14",
    camera:"M4 7h3l1.5-2h7L17 7h3a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1Zm8 3.2a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z",
    wand:"m15 4 5 5M4 20l9.5-9.5M5 5l1 2 2 1-2 1-1 2-1-2-2-1 2-1 1-2Zm11 10 1 2 2 1-2 1-1 2-1-2-2-1 2-1 1-2Z", heart:"M20 8.5c0 5-8 9.5-8 9.5S4 13.5 4 8.5A4.5 4.5 0 0 1 12 6a4.5 4.5 0 0 1 8 2.5Z", refresh:"M20 11a8 8 0 1 0 2 5m-2-5v-5m0 5h-5", check:"m5 12 4 4L19 6", x:"M6 6l12 12M18 6 6 18", sliders:"M4 7h16M4 17h16M8 4v6M16 14v6"
  };
  return <svg viewBox="0 0 24 24" className="icon"><path d={p[name] || p.plus} fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}

function Header({ go, title, back }: { go:(s:Screen)=>void; title?:string; back?:Screen }) {
  return <header className="brand-header"><div className="brand-left">{back ? <button className="round-btn" onClick={()=>go(back)}><Icon name="back"/></button> : <div className="brand-mark">⌁</div>}<span className={title?"screen-title":"wordmark"}>{title || "Percha"}</span></div><span className="ai-badge">✦ AI Assist</span></header>;
}
function BottomNav({ screen, go }: {screen:Screen;go:(s:Screen)=>void}) {
  return <nav className="bottom-nav"><button className={screen==="inicio"?"active":""} onClick={()=>go("inicio")}><Icon name="home"/><span>Inicio</span></button><button className={["armario","armario-abierto","categorias","detalle","anadir"].includes(screen)?"active":""} onClick={()=>go("armario")}><Icon name="closet"/><span>Armario</span></button><button className={["outfits","resultado","editor"].includes(screen)?"active":""} onClick={()=>go("outfits")}><Icon name="outfits"/><span>Outfits</span></button><button className={screen==="ajustes"?"active":""} onClick={()=>go("ajustes")}><Icon name="settings"/><span>Ajustes</span></button></nav>;
}
function Photo({ emoji, className="", src }: {emoji?:string;className?:string;src?:string}) { return <div className={`fashion-image ${className}`}>{src ? <img src={src} alt="Prenda"/> : <span>{emoji || "👕"}</span>}</div>; }
function Pills({items, selected, onSelect}:{items:string[];selected?:string;onSelect?:(x:string)=>void}) { return <div className="pills">{items.map(x=><button key={x} className={selected===x?"selected":""} onClick={()=>onSelect?.(x)}>{x}</button>)}</div>; }

export default function Home(){
 const [screen,setScreen]=useState<Screen>("inicio");
 const [garments,setGarments]=useState<Garment[]>([]);
 const [outfits,setOutfits]=useState<SavedOutfit[]>([]);
 const [settings,setSettings]=useState<AppSettings>(wardrobeStore.getSettings());
 const [selectedId,setSelectedId]=useState<string|null>(null);
 const [category,setCategory]=useState("Todos");
 const [occasion,setOccasion]=useState("Casual");
 const [style,setStyle]=useState(settings.style || "Minimalista");
 const [draftName,setDraftName]=useState("");
 const [draftType,setDraftType]=useState("Tops");
 const [draftSize,setDraftSize]=useState("M");
 const [draftOccasions,setDraftOccasions]=useState<string[]>(["Informal"]);
 const [draftImage,setDraftImage]=useState<string|undefined>();
 const [generatedIds,setGeneratedIds]=useState<string[]>([]);
 const [filter,setFilter]=useState("Todos");
 const fileRef=useRef<HTMLInputElement>(null);
 const go=(s:Screen)=>setScreen(s);

 useEffect(()=>{ setGarments(wardrobeStore.getGarments()); setOutfits(wardrobeStore.getOutfits()); setSettings(wardrobeStore.getSettings()); },[]);
 const selected=garments.find(x=>x.id===selectedId) || null;
 const filteredGarments=useMemo(()=>garments.filter(g=>category==="Todos" || g.category===category).filter(g=>filter==="Todos" || g.occasions.includes(filter)),[garments,category,filter]);
 const refresh=()=>{setGarments(wardrobeStore.getGarments());setOutfits(wardrobeStore.getOutfits());setSettings(wardrobeStore.getSettings());};
 const saveGarment=()=>{
   const name=draftName.trim() || "Prenda sin nombre";
   const garment:Garment={id:makeId("garment"),name,type:draftType,size:draftSize,category:draftType,occasions:draftOccasions.length?draftOccasions:["Informal"],color:"Sin especificar",season:"Todo el año",image:draftImage,createdAt:Date.now(),wornCount:0};
   wardrobeStore.saveGarment(garment); refresh(); setSelectedId(garment.id); setDraftName(""); setDraftImage(undefined); go("armario-abierto");
 };
 const onFile=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setDraftImage(String(reader.result));reader.readAsDataURL(file);};
 const toggleDraftOccasion=(x:string)=>setDraftOccasions(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);
 const toggleFav=()=>{if(!selected)return;wardrobeStore.toggleFavorite(selected.id);refresh();};
 const generate=()=>{const pool=garments.filter(g=>g.occasions.includes(occasion) || g.occasions.length===0);const chosen=(pool.length?pool:garments).slice(0,4);setGeneratedIds(chosen.map(g=>g.id));go("resultado");};
 const saveGenerated=()=>{if(!generatedIds.length)return;const outfit:SavedOutfit={id:makeId("outfit"),name:`Outfit ${new Date().toLocaleDateString("es-ES")}`,type:occasion,garmentIds:generatedIds,createdAt:Date.now()};wardrobeStore.saveOutfit(outfit);wardrobeStore.addHistory(outfit.name);refresh();go("outfits");};
 const clearData=()=>{if(confirm("¿Borrar todas tus prendas, outfits e historial?")){wardrobeStore.clearAll();refresh();setSelectedId(null);go("inicio");}};
 const updateSettings=(patch:Partial<AppSettings>)=>{const next={...settings,...patch};setSettings(next);wardrobeStore.saveSettings(next);};

 return <main className="app-shell"><div className="phone">
 {screen==="inicio" && <><div className="scroll-content"><Header go={go}/><section className="hero"><Photo emoji="🧥" className="hero-image"/><h1>Tu armario<br/>inteligente</h1><p>Organiza tus prendas, redescubre tu estilo y genera los outfits perfectos para cada ocasión con nuestro asistente de moda virtual.</p><button className="primary-btn" onClick={()=>go("armario")}>Abrir mi armario <Icon name="arrow"/></button><button className="secondary-btn large" onClick={()=>go("generador")}><Icon name="wand"/> ¿Qué me pongo hoy?</button><div className="stats"><b>{garments.length}</b> Prendas listas<i/><b>{outfits.length}</b> Outfits creados</div></section></div><BottomNav screen={screen} go={go}/></>}

 {screen==="armario" && <><div className="scroll-content closet-screen"><div className="status-space"/><div className="center-title"><h2>Mi Armario</h2><span>OTOÑO / INVIERNO</span></div><button className="closed-cabinet" onClick={()=>go("armario-abierto")}><div/><div/><span>Toca para abrir</span></button><div className="side-actions"><button onClick={()=>setFilter(filter==="Todos"?"Elegante":"Todos")}><Icon name="sliders"/><small>{garments.length}</small></button><button onClick={()=>go("categorias")}><Icon name="search"/></button></div></div><BottomNav screen={screen} go={go}/></>}

 {screen==="armario-abierto" && <><div className="scroll-content"><Header go={go} title="Mi Armario"/><div className="filter-scroll">{["Todos",...occasions].map(x=><button className={filter===x?"selected":""} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><section className="wardrobe-card">{categoryNames.map(name=>{const count=garments.filter(g=>g.category===name).length;return <button className="wardrobe-row" key={name} onClick={()=>{setCategory(name);go("categorias")}}><Photo emoji={categoryEmoji[name]}/><div><small>{name.toUpperCase()}</small><strong>{name}</strong></div><em>{count} {name==="Zapatos"?"pares":"prendas"}</em></button>})}</section>{garments.length===0&&<p className="helper">Tu armario está vacío. Pulsa + para añadir tu primera prenda.</p>}<button className="fab" onClick={()=>go("anadir")}><Icon name="plus"/></button></div><BottomNav screen={screen} go={go}/></>}

 {screen==="categorias" && <><div className="scroll-content"><Header title="Categorías" go={go}/><span className="subheading">MI ARMARIO</span><div className="search"><Icon name="search"/>Buscar prendas...</div><section className="category-grid">{categoryNames.map(name=>{const list=garments.filter(g=>g.category===name);return <button key={name} onClick={()=>{setCategory(name);if(list[0]){setSelectedId(list[0].id);go("detalle")}else go("anadir")}}><Photo emoji={categoryEmoji[name]} src={list[0]?.image}/><strong>{name}</strong><small>{list.length} prendas</small></button>})}</section></div><BottomNav screen={screen} go={go}/></>}

 {screen==="detalle" && <><div className="scroll-content"><Header title="DETALLE DE PRENDA" back="categorias" go={go}/>{selected?<><Photo emoji="👕" src={selected.image} className="detail-image"/><section className="detail-body"><div className="detail-brand">{selected.color.toUpperCase()} <button onClick={toggleFav}><Icon name="heart"/></button></div><h2>{selected.name}</h2><Pills items={[selected.color,`Talla ${selected.size}`,selected.season]}/><h4>OCASIONES RECOMENDADAS</h4><Pills items={selected.occasions}/><div className="metrics"><div>Puesta<strong>{selected.wornCount} veces</strong></div><div>Creada<strong>{new Date(selected.createdAt).toLocaleDateString("es-ES")}</strong></div></div><div className="detail-actions"><button className="secondary-square" onClick={()=>{wardrobeStore.deleteGarment(selected.id);refresh();go("categorias")}}><Icon name="x"/></button><button className="primary-btn" onClick={()=>{setOccasion(selected.occasions[0]||"Casual");go("generador")}}><Icon name="wand"/>Generar Outfit con esta prenda</button></div></section></>:<p className="helper">No hay ninguna prenda guardada todavía.</p>}</div><BottomNav screen={screen} go={go}/></>}

 {screen==="anadir" && <><div className="scroll-content"><Header title="Añadir Prenda" go={go}/><section className="add-body"><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={onFile} hidden/><button className="upload-zone" onClick={()=>fileRef.current?.click()}>{draftImage?<Photo src={draftImage}/>:<div className="camera-circle"><Icon name="camera"/></div>}<strong>{draftImage?"Foto seleccionada":"Sube o toma una foto"}</strong><small>Soporta JPG, PNG en fondo claro</small></button><div className="ai-banner">✦ <span>La IA detectará automáticamente tipo, color y estilo de tu prenda al subir la imagen.</span></div><div className="form"><label>Nombre de la Prenda<input value={draftName} onChange={e=>setDraftName(e.target.value)} placeholder="Jersey de Punto Cuello V"/></label><label>Tipo de Prenda<select value={draftType} onChange={e=>setDraftType(e.target.value)}><option>Tops</option><option>Pantalones</option><option>Vestidos</option><option>Faldas</option><option>Abrigos</option><option>Zapatos</option><option>Bolsos</option><option>Accesorios</option></select></label><label>Talla<select value={draftSize} onChange={e=>setDraftSize(e.target.value)}><option>M</option><option>S</option><option>L</option><option>XL</option><option>Única</option></select></label><label>Ocasiones recomendadas<div className="chip-row">{occasions.map(x=><button type="button" className={draftOccasions.includes(x)?"selected":""} key={x} onClick={()=>toggleDraftOccasion(x)}>{x}</button>)}</div></label></div><button className="primary-btn" onClick={saveGarment}>Guardar Prenda</button></section></div><BottomNav screen={screen} go={go}/></>}

 {screen==="generador" && <><div className="scroll-content"><Header title="Generador AI" go={go}/><section className="generator"><h3>¿PARA QUÉ OCASIÓN?</h3><div className="occasion-grid">{["Casual","Trabajo","Cita","Eventos","Deporte"].map(x=><button className={occasion===x?"selected":""} key={x} onClick={()=>setOccasion(x)}>{x}</button>)}</div><h3>CLIMA ACTUAL</h3><div className="weather"><span>☁</span><div>Ligeramente frío<small>Gran Canaria, Otoño</small></div><strong>16°C</strong></div><h3>PREFERENCIA DE ESTILO</h3><div className="style-toggle">{["Minimalista","Atrevido","Clásico"].map(x=><button className={style===x?"selected":""} key={x} onClick={()=>setStyle(x)}>{x}</button>)}</div><button className="primary-btn generate" onClick={generate} disabled={!garments.length}><Icon name="wand"/>Generar Outfit Inteligente ✨</button><p className="helper">{garments.length?`Basado en tus ${garments.length} prendas y tus preferencias.`:"Añade al menos una prenda para generar un outfit."}</p></section></div><BottomNav screen={screen} go={go}/></>}

 {screen==="resultado" && <><div className="scroll-content"><Header title="TU OUTFIT AI" back="generador" go={go}/><span className="match">{generatedIds.length?"100% Match":"Sin prendas"}</span><section className="outfit-result"><div className="outfit-stack">{generatedIds.map(id=>{const g=garments.find(x=>x.id===id);return <Photo key={id} emoji={categoryEmoji[g?.category||"Tops"]} src={g?.image}/>})}</div><div className="outfit-labels">{generatedIds.map(id=>{const g=garments.find(x=>x.id===id);return <span key={id}>{g?.category}<strong>{g?.name}</strong></span>})}</div></section><div className="result-actions"><button onClick={generate}><Icon name="refresh"/></button><button className="primary-btn" onClick={saveGenerated} disabled={!generatedIds.length}><Icon name="check"/>Guardar este look</button></div></div><BottomNav screen={screen} go={go}/></>}

 {screen==="editor" && <><div className="scroll-content"><Header title="EDITAR OUTFIT" back="resultado" go={go}/><button className="reset" onClick={()=>setGeneratedIds([])}>Reset</button><section className="editor-stack">{generatedIds.map(id=>{const g=garments.find(x=>x.id===id);return <div className="editor-slot" key={id}><div className="slot-head"><b>{g?.category}</b><span>⌁</span></div><div className="current-item"><Photo emoji={categoryEmoji[g?.category||"Tops"]} src={g?.image}/><div><strong>{g?.name}</strong><small>Talla {g?.size}</small></div><button onClick={()=>setGeneratedIds(v=>v.filter(x=>x!==id))}><Icon name="x"/></button></div></div>})}</section><button className="primary-btn confirm" onClick={saveGenerated}>Confirmar Cambios</button></div><BottomNav screen={screen} go={go}/></>}

 {screen==="outfits" && <><div className="scroll-content"><Header title="Mis Outfits" go={go}/><div className="outfit-tabs"><button className="active">Todos</button><button onClick={()=>setOutfits(wardrobeStore.getOutfits().filter(x=>x.favorite))}>Favoritos</button><button onClick={()=>refresh()}>Recientes</button></div><section className="saved-outfits">{outfits.map(o=><button className="saved-card" key={o.id} onClick={()=>{setGeneratedIds(o.garmentIds);go("resultado")}}><Photo emoji="🧥" src={garments.find(g=>g.id===o.garmentIds[0])?.image}/><div><strong>{o.name}</strong><small>{o.type}</small></div><span>{o.favorite?"♥":"♡"}</span></button>)}</section>{!outfits.length&&<p className="helper">Todavía no tienes outfits guardados.</p>}<button className="fab" onClick={()=>go("generador")}><Icon name="plus"/></button></div><BottomNav screen={screen} go={go}/></>}

 {screen==="historial" && <><div className="scroll-content"><Header title="Historial" go={go}/><div className="history-head"><strong>Actividad reciente</strong><button onClick={()=>wardrobeStore.getHistory()}>Actualizar</button></div><section className="history-list">{wardrobeStore.getHistory().map((x,i)=><article key={`${x}-${i}`}><Photo emoji="🧥"/><div><strong>{x}</strong><small>Guardado en tu historial</small></div><span>Outfit</span></article>)}</section><p className="helper">El historial se guarda localmente en este dispositivo.</p></div><BottomNav screen={screen} go={go}/></>}

 {screen==="ajustes" && <><div className="scroll-content"><Header title="Ajustes" go={go}/><section className="profile"><div className="avatar">{(settings.displayName||"MP").slice(0,2).toUpperCase()}</div><div><strong>{settings.displayName}</strong><small>{settings.email || "Sin correo configurado"}</small></div><span>Premium</span></section><div className="settings-group"><h4>MI CUENTA</h4><button onClick={()=>{const name=prompt("¿Cómo quieres que aparezca tu nombre?",settings.displayName);if(name)updateSettings({displayName:name})}}><span>Información Personal</span><small>›</small></button><button onClick={()=>alert("La suscripción estará disponible cuando conectemos la cuenta de usuario.")}><span>Suscripción Premium</span><small>›</small></button><button onClick={()=>{const next=prompt("Preferencia de estilo",style);if(next){setStyle(next);updateSettings({style:next})}}}><span>Preferencias de Estilo</span><small>›</small></button></div><div className="settings-group"><h4>UTILIDADES</h4><button onClick={()=>updateSettings({assistantEnabled:!settings.assistantEnabled})}><span>Ajustar mi Asistente AI</span><small>{settings.assistantEnabled?"Activo":"Inactivo"}</small></button><button onClick={()=>{const data=JSON.stringify({garments,outfits,settings},null,2);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type:"application/json"}));a.download="percha-datos.json";a.click();URL.revokeObjectURL(a.href)}}><span>Exportar Datos de Armario</span><small>›</small></button><button onClick={clearData}><span>Borrar todos mis datos</span><small>›</small></button></div><div className="settings-group"><h4>SOPORTE</h4><button onClick={()=>alert("PERCHA: tus datos se guardan localmente en este dispositivo.")}><span>Ayuda y Soporte</span><small>›</small></button></div></div><BottomNav screen={screen} go={go}/></>}
 </div></main>;
}
