'use client';
import { useEffect, useMemo, useState } from 'react';
import { usePerchaStore } from '@/store/usePerchaStore';
import type { Category, Occasion } from '@/types/garment';
type Screen='inicio'|'armario'|'armario-abierto'|'categorias'|'lista'|'detalle'|'anadir'|'generador'|'outfits'|'ajustes';
const categoryMap:Record<string,Category>={Tops:'top',Vestidos:'dress',Pantalones:'bottom',Faldas:'bottom',Abrigos:'outerwear',Zapatos:'shoes',Bolsos:'accessory',Accesorios:'accessory'};
const categoryNames:Record<string,string>={top:'Parte de arriba',bottom:'Parte de abajo',dress:'Vestidos',outerwear:'Abrigos',shoes:'Calzado',accessory:'Accesorios',cap:'Gorras'};
function Icon({name}:{name:string}){const p:Record<string,string>={home:'M3 10.5 12 3l9 7.5v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z',closet:'M5 4h14v16H5z M8 8h2 M14 8h2 M8 12h8 M8 16h8',outfits:'M6 4h12v16H6z M9 8h6 M9 12h6 M9 16h4',settings:'M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm0-5v2m0 13v2M2 12h2m16 0h2',arrow:'M5 12h13m-5-5 5 5-5 5',back:'M19 12H5m6-6-6 6 6 6',plus:'M12 5v14M5 12h14',heart:'M20 8.5c0 5-8 9.5-8 9.5S4 13.5 4 8.5A4.5 4.5 0 0 1 12 6a4.5 4.5 0 0 1 8 2.5Z',wand:'m15 4 5 5M4 20l9.5-9.5M5 5l1 2 2 1-2 1-1 2-1-2-2-1 2-1 1-2Zm11 10 1 2 2 1-2 1-1 2-1-2-2-1 2-1 1-2Z'};return <svg viewBox="0 0 24 24" className="icon"><path d={p[name]||p.plus} fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function Header({go,title,back}:{go:(s:Screen)=>void;title?:string;back?:Screen}){return <header className="brand-header"><div className="brand-left">{back?<button className="round-btn" onClick={()=>go(back)}><Icon name="back"/></button>:<div className="brand-mark">⌁</div>}<span className={title?'screen-title':'wordmark'}>{title||'Percha'}</span></div><span className="ai-badge">✦ AI Assist</span></header>}
function BottomNav({screen,go}:{screen:Screen;go:(s:Screen)=>void}){return <nav className="bottom-nav"><button className={screen==='inicio'?'active':''} onClick={()=>go('inicio')}><Icon name="home"/><span>Inicio</span></button><button className={['armario','armario-abierto','categorias','lista','detalle','anadir'].includes(screen)?'active':''} onClick={()=>go('armario')}><Icon name="closet"/><span>Armario</span></button><button className={screen==='outfits'?'active':''} onClick={()=>go('outfits')}><Icon name="outfits"/><span>Outfits</span></button><button className={screen==='ajustes'?'active':''} onClick={()=>go('ajustes')}><Icon name="settings"/><span>Ajustes</span></button></nav>}
function Photo({image,emoji='👕',className=''}:{image?:string;emoji?:string;className?:string}){return <div className={`fashion-image ${className}`}>{image?<img src={image} alt=""/>:<span>{emoji}</span>}</div>}
export default function Home(){const {garments,outfits,initialized,init,toggleFavorite,cycleStatus,addGarment,deleteGarment,deleteOutfit}=usePerchaStore();const [screen,setScreen]=useState<Screen>('inicio');const [filter,setFilter]=useState<Category|null>(null);const [selected,setSelected]=useState<string>();const [occasion,setOccasion]=useState<Occasion>('informal');const [form,setForm]=useState({name:'',category:'top' as Category,occasion:'informal' as Occasion,image:''});useEffect(()=>{void init()},[init]);const go=(s:Screen)=>setScreen(s);const visible=useMemo(()=>filter?garments.filter(g=>g.category===filter):garments,[garments,filter]);const save=async()=>{if(!form.name.trim())return;await addGarment({id:crypto.randomUUID(),name:form.name.trim(),category:form.category,occasion:form.occasion,status:'disponible',favorite:false,addedAt:Date.now(),image:form.image||undefined});setForm({name:'',category:'top',occasion:'informal',image:''});go('lista')};if(!initialized)return <main className="app-shell"><div className="phone"><div className="scroll-content"><Header go={go}/><section className="hero"><h1>Preparando tu armario…</h1></section></div></div></main>;const selectedGarment=garments.find(g=>g.id===selected);return <main className="app-shell"><div className="phone">
{screen==='inicio'&&<><div className="scroll-content"><Header go={go}/><section className="hero"><Photo emoji="🧥" className="hero-image"/><h1>Tu armario<br/>inteligente</h1><p>Organiza tus prendas, redescubre tu estilo y genera los outfits perfectos para cada ocasión con nuestro asistente de moda virtual.</p><button className="primary-btn" onClick={()=>go('armario')}>Abrir mi armario <Icon name="arrow"/></button><button className="secondary-btn large" onClick={()=>go('generador')}><Icon name="wand"/> ¿Qué me pongo hoy?</button><div className="stats"><b>{garments.length}</b> Prendas listas<i/><b>{outfits.length}</b> Outfits creados</div></section></div><BottomNav screen={screen} go={go}/></>}
{screen==='armario'&&<><div className="scroll-content closet-screen"><div className="status-space"/><div className="center-title"><h2>Mi Armario</h2><span>MI COLECCIÓN</span></div><button className="closed-cabinet" onClick={()=>go('armario-abierto')}><div/><div/><span>Toca para abrir</span></button></div><BottomNav screen={screen} go={go}/></>}
{screen==='armario-abierto'&&<><div className="scroll-content"><Header go={go} title="Mi Armario"/><div className="filter-scroll">{['Informal','Salir','Elegante','Noche','Trabajo','Evento'].map(x=><button key={x} onClick={()=>go('lista')}>{x}</button>)}</div><section className="wardrobe-card">{[['🧥','ABRIGOS','Abrigos','outerwear'],['👕','BARRA SUPERIOR','Parte de arriba','top'],['👗','BARRA MEDIA','Vestidos y Enteros','dress'],['👖','CAJÓN PRINCIPAL','Parte de abajo','bottom'],['🕶️','CAJÓN PEQUEÑO','Accesorios','accessory'],['👟','ZONA INFERIOR','Calzado','shoes']].map(([e,sub,name,c])=><button className="wardrobe-row" key={String(name)} onClick={()=>{setFilter(c as Category);go('lista')}}><Photo emoji={String(e)}/><div><small>{sub}</small><strong>{name}</strong></div><em>{garments.filter(g=>g.category===c).length} prendas</em></button>)}</section><button className="fab" onClick={()=>go('anadir')}><Icon name="plus"/></button></div><BottomNav screen={screen} go={go}/></>}
{screen==='categorias'&&<><div className="scroll-content"><Header title="Categorías" go={go}/><span className="subheading">MI ARMARIO</span><section className="category-grid">{Object.entries(categoryMap).map(([name,c])=><button key={name} onClick={()=>{setFilter(c);go('lista')}}><Photo emoji={name==='Vestidos'?'👗':name==='Zapatos'?'👟':name==='Abrigos'?'🧥':'👕'}/><strong>{name}</strong><small>{garments.filter(g=>g.category===c).length} prendas</small></button>)}</section></div><BottomNav screen={screen} go={go}/></>}
{screen==='lista'&&<><div className="scroll-content"><Header title="Mi Armario" back="armario-abierto" go={go}/><div className="filter-scroll"><button className={!filter?'selected':''} onClick={()=>setFilter(null)}>Todas</button>{Object.entries(categoryNames).map(([c,n])=><button key={c} className={filter===c?'selected':''} onClick={()=>setFilter(c as Category)}>{n}</button>)}</div><section className="saved-outfits">{visible.map(g=><button className="saved-card" key={g.id} onClick={()=>{setSelected(g.id);go('detalle')}}><Photo image={g.image}/><div><strong>{g.name}</strong><small>{categoryNames[g.category]}</small></div><span onClick={e=>{e.stopPropagation();void toggleFavorite(g.id)}}>{g.favorite?'♥':'♡'}</span></button>)}{!visible.length&&<div className="empty-state"><strong>Tu armario está vacío.</strong><span>Añade tu primera prenda.</span></div>}</section><button className="fab" onClick={()=>go('anadir')}><Icon name="plus"/></button></div><BottomNav screen={screen} go={go}/></>}
{screen==='detalle'&&selectedGarment&&<><div className="scroll-content"><Header title="DETALLE DE PRENDA" back="lista" go={go}/><Photo image={selectedGarment.image} emoji="👕" className="detail-image"/><section className="detail-body"><div className="detail-brand">{categoryNames[selectedGarment.category]} <button onClick={()=>void toggleFavorite(selectedGarment.id)}><Icon name="heart"/></button></div><h2>{selectedGarment.name}</h2><div className="pills"><span>{selectedGarment.occasion}</span><span>{selectedGarment.status}</span></div><div className="detail-actions"><button className="secondary-square" onClick={()=>void cycleStatus(selectedGarment.id)}>Estado</button><button className="primary-btn" onClick={()=>void toggleFavorite(selectedGarment.id)}>{selectedGarment.favorite?'Quitar favorito':'Añadir favorito'}</button></div><button className="danger-action" onClick={()=>{void deleteGarment(selectedGarment.id);setSelected(undefined);go('lista')}}>Eliminar prenda</button></section></div><BottomNav screen={screen} go={go}/></>}
{screen==='anadir'&&<><div className="scroll-content"><Header title="Añadir Prenda" back="armario-abierto" go={go}/><section className="add-body"><label>Foto<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setForm(v=>({...v,image:String(r.result)}));r.readAsDataURL(f)}}/></label>{form.image&&<Photo image={form.image}/>}<div className="form"><label>Nombre de la Prenda<input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="Ej. Camiseta blanca"/></label><label>Tipo de Prenda<select value={form.category} onChange={e=>setForm(v=>({...v,category:e.target.value as Category}))}><option value="top">Parte de arriba</option><option value="bottom">Parte de abajo</option><option value="dress">Vestido</option><option value="outerwear">Abrigo</option><option value="shoes">Calzado</option><option value="accessory">Accesorio</option></select></label><label>Ocasión<select value={form.occasion} onChange={e=>setForm(v=>({...v,occasion:e.target.value as Occasion}))}><option value="informal">Informal</option><option value="salir">Salir</option><option value="elegante">Elegante</option><option value="trabajo">Trabajo</option><option value="evento">Evento</option></select></label></div><button className="primary-btn" onClick={()=>void save()}>Guardar Prenda</button></section></div><BottomNav screen={screen} go={go}/></>}
{screen==='generador'&&<><div className="scroll-content"><Header title="Generador AI" back="inicio" go={go}/><section className="generator"><h3>¿PARA QUÉ OCASIÓN?</h3><div className="occasion-grid">{['informal','trabajo','salir','evento','deporte'].map(x=><button key={x} className={occasion===x?'selected':''} onClick={()=>setOccasion(x as Occasion)}>{x}</button>)}</div><button className="primary-btn generate" onClick={()=>go('outfits')}><Icon name="wand"/>Ver mis conjuntos</button><p className="helper">Usando tus {garments.length} prendas reales.</p></section></div><BottomNav screen={screen} go={go}/></>}
{screen==='outfits'&&<><div className="scroll-content"><Header title="Mis Outfits" go={go}/><section className="saved-outfits">{outfits.map(o=><button className="saved-card" key={o.id}><Photo emoji="✨"/><div><strong>{o.name}</strong><small>{o.garmentIds.length} prendas</small></div><span onClick={e=>{e.stopPropagation();if(confirm(`¿Eliminar ${o.name}?`))void deleteOutfit(o.id)}}>🗑</span></button>)}{!outfits.length&&<div className="empty-state"><strong>Aún no tienes outfits.</strong><span>Los conjuntos guardados aparecerán aquí.</span></div>}</section></div><BottomNav screen={screen} go={go}/></>}
{screen==='ajustes'&&<><div className="scroll-content"><Header title="Ajustes" go={go}/><section className="add-body"><button className="secondary-btn" onClick={()=>{localStorage.removeItem('percha-store');location.reload()}}>Restablecer datos locales</button><p className="helper">Tus prendas se guardan localmente en este dispositivo.</p></section></div><BottomNav screen={screen} go={go}/></>}
</div></main>
}