'use client';

import { useEffect, useMemo, useState } from 'react';
import { usePerchaStore } from '@/store/usePerchaStore';
import { Category, Status } from '@/types/garment';
import { WallScene } from '@/components/views/WallScene';
import { ClosetStage } from '@/components/views/ClosetStage';
import { GarmentModal } from '@/components/modals/GarmentModal';

const categoryLabels: Record<Category, string> = { top:'Parte de arriba', bottom:'Parte de abajo', dress:'Vestido / mono', outerwear:'Abrigo / chaqueta', shoes:'Calzado', accessory:'Accesorio', cap:'Gorras' };
const statusLabels: Record<Status,string> = { disponible:'Disponible', lavando:'Lavando', no_quiero:'No me la quiero poner' };
type CategoryFilter = Category | 'top-dress' | 'accessory-cap' | null;

export default function Home(){
 const {garments,outfits,initialized,init,toggleFavorite,cycleStatus,addGarment,updateGarment,deleteGarment}=usePerchaStore();
 const [screen,setScreen]=useState<'wall'|'closet'|'list'>('wall'); const [categoryFilter,setCategoryFilter]=useState<CategoryFilter>(null); const [statusFilter,setStatusFilter]=useState<'todas'|'favoritos'|Status>('todas'); const [modal,setModal]=useState<'create'|'edit'|null>(null); const [editingId,setEditingId]=useState<string>();
 useEffect(()=>{void init()},[init]);
 const filtered=useMemo(()=>garments.filter(g=>{const categoryOk=!categoryFilter||(categoryFilter==='top-dress'?g.category==='top'||g.category==='dress':categoryFilter==='accessory-cap'?g.category==='accessory'||g.category==='cap':g.category===categoryFilter);const statusOk=statusFilter==='todas'||(statusFilter==='favoritos'?g.favorite:g.status===statusFilter);return categoryOk&&statusOk}),[garments,categoryFilter,statusFilter]);
 const editing=editingId?garments.find(g=>g.id===editingId):undefined;
 if(!initialized)return <main className="percha-shell"><p className="muted">Cargando tu armario…</p></main>;
 if(screen==='list')return <main className="percha-shell"><header className="app-header"><button className="back-button" onClick={()=>setScreen('closet')}>←</button><div><h1>Armario</h1><p>{filtered.length} prendas</p></div><button className="primary-action small" onClick={()=>{setEditingId(undefined);setModal('create')}}>+ Añadir</button></header><nav className="filter-row">{(['todas','favoritos','disponible','lavando','no_quiero'] as const).map(v=><button key={v} className={statusFilter===v?'filter active':'filter'} onClick={()=>setStatusFilter(v)}>{v==='todas'?'Todas':v==='favoritos'?'Favoritos':statusLabels[v]}</button>)}</nav><section className="garment-grid">{filtered.length?filtered.map(g=><article className="garment-card" key={g.id}><div className="garment-image">{g.image?<img src={g.image} alt={g.name} loading="lazy"/>:<span>sin foto</span>}<button className="icon-button" onClick={()=>void toggleFavorite(g.id)}>{g.favorite?'♥':'♡'}</button></div><div className="garment-info"><strong>{g.name}</strong><small>{categoryLabels[g.category]}</small><button className="status-button" onClick={()=>void cycleStatus(g.id)}>{statusLabels[g.status]}</button><div className="card-actions"><button onClick={()=>{setEditingId(g.id);setModal('edit')}}>Editar</button><button onClick={()=>{if(confirm(`¿Eliminar ${g.name}?`))void deleteGarment(g.id)}}>Eliminar</button></div></div></article>):<div className="empty-state"><strong>No hay prendas aquí.</strong><span>Prueba otro filtro o añade una.</span></div>}</section><footer className="data-footer">{outfits.length} conjuntos guardados · datos locales conectados</footer><GarmentModal open={modal!==null} initial={editing} onClose={()=>{setModal(null);setEditingId(undefined)}} onSave={async data=>{if(data.id){await updateGarment(data.id,data)}else{await addGarment({id:crypto.randomUUID(),name:data.name,category:data.category,occasion:data.occasion,status:'disponible',favorite:data.favorite,addedAt:Date.now(),image:data.image,_pendingDataUrl:data._pendingDataUrl})}}}/></main>;
 return <main className="percha-shell"><div className="view-switcher"><button className={screen==='wall'?'active':''} onClick={()=>setScreen('wall')}>Inicio</button><button className={screen==='closet'?'active':''} onClick={()=>setScreen('closet')}>Armario</button></div>{screen==='wall'?<WallScene onCloset={()=>setScreen('closet')} onHistory={()=>setScreen('list')} onToday={()=>setScreen('list')}/>:<ClosetStage onCategory={c=>{setCategoryFilter(c);setStatusFilter('todas');setScreen('list')}} onLaundry={()=>{setCategoryFilter(null);setStatusFilter('lavando');setScreen('list')}} onTrash={()=>{setCategoryFilter(null);setStatusFilter('no_quiero');setScreen('list')}}/>}</main>;
}
